// AUTO-GENERATED BY GITHUB ACTIONS
const gpxLibrary = [
    {
        "filename": "Zwift_Race_Stage_5_Zwift_Games_Three_Step_Sisters_C_.gpx",
        "name": "Zwift - Race: Stage 5: Zwift Games: Three Step Sisters (C)"
    },
    {
        "filename": "road_to_sky.gpx",
        "name": "Zwift - Zone 2 - 74% (90 min)"
    },
    {
        "filename": "Zwift_Zone_2_74_90_min_-trimmed.gpx",
        "name": "Zwift_Zone_2_74_90_min_-trimmed"
    }
];