// AUTO-GENERATED BY GITHUB ACTIONS
const gpxLibrary = [
    {
        "filename": "road_to_sky.gpx",
        "name": "Zwift - Zone 2 - 74% (90 min)"
    },
    {
        "filename": "Zwift_Zone_2_74_90_min_-trimmed.gpx",
        "name": "Zwift_Zone_2_74_90_min_-trimmed"
    },
    {
        "filename": "epic_kom.gpx",
        "name": "Zwift_Zone_2_74_90_min_-trimmed"
    }
];